### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by fedir** [craicoverflow/go-environment-variables-example#1]
As any package in golang, configuration module also should be the subject of unit tests implementation. Otherwise, You could have some important surprises in production, depending on the variations of multiple factors and variables formats.

**Comment by craicoverflow** [comment]
Hi @fedir - I fully agree.

However, this is not a package to be installed. This is just the code used in a blog post - [A no-nonsense guide to environment variables in Go](https://endaphelan.me/guides/golang/a-no-nonsense-guide-to-environment-variables-in-go/)
